input {
  file {
    path => "D:/Documents/Data/json/*.json"
    start_position => "beginning"
    sincedb_path => "NUL"
  }
}

filter {
  json {
    source => "message"
  }
  mutate {
    remove_field => ["message", "path", "host", "@version", "[event][original]", "[log][file][path]"]
  }
  ruby {
    code => 'require "digest/md5"; event.set("[@metadata][_id]", Digest::MD5.hexdigest(event.get("[d]").to_s + event.get("[u]").to_s + event.get("[p]").to_s))'
  }
}

output {
  elasticsearch {
    hosts => "192.168.137.20:9200"
    index => "urluserpass"
    user => "elastic"
    password => "Dat1999@"
    ssl_enabled => false
    document_id => "%{[@metadata][_id]}"
  }
  stdout {}
}
